rudak_partner_front:
    path:     /partenaires-du-rcm
    defaults: { _controller: "RudakPartnerBundle:Default:index" }

rudak_partner_show:
    path:     /partenaires-du-rcm/{id}/{slug}
    defaults: { _controller: "RudakPartnerBundle:Default:show" }

rudak_partner_admin_partners:
    resource: "@RudakPartnerBundle/Resources/config/routing/partner.yml"
    prefix:   /admin/partners

rudak_partner_admin_partners_categ:
    resource: "@RudakPartnerBundle/Resources/config/routing/category.yml"
    prefix:   /admin/partners/categ

