<?php

namespace Rudak\PartnerBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * CategoryRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CategoryRepository extends EntityRepository
{
    public function getCategories()
    {
        $qb = $this->createQueryBuilder('c')
            ->addSelect('p,pic')
            ->leftJoin('c.partners', 'p')
            ->leftJoin('p.picture', 'pic')
            ->where('p.current = :current')->setParameter('current', true)
            ->getQuery();
        return $qb->execute();
    }
}
