<?php

namespace Rudak\PartnerBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * PartnerRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PartnerRepository extends EntityRepository
{
    public function getPartnersList()
    {
        $qb = $this->createQueryBuilder('p')
            ->addSelect('pic')
            ->addSelect('c')
            ->leftJoin('p.picture', 'pic')
            ->leftJoin('p.category', 'c')
            ->orderBy('p.category', 'ASC')
            ->addOrderBy('p.id', 'DESC')
            ->getQuery();
        return $qb->execute();
    }
}
