admin_partners_categ:
    path:     /
    defaults: { _controller: "RudakPartnerBundle:Category:index" }

admin_partners_categ_show:
    path:     /{id}/show
    defaults: { _controller: "RudakPartnerBundle:Category:show" }

admin_partners_categ_new:
    path:     /new
    defaults: { _controller: "RudakPartnerBundle:Category:new" }

admin_partners_categ_create:
    path:     /create
    defaults: { _controller: "RudakPartnerBundle:Category:create" }
    requirements: { _method: post }

admin_partners_categ_edit:
    path:     /{id}/edit
    defaults: { _controller: "RudakPartnerBundle:Category:edit" }

admin_partners_categ_update:
    path:     /{id}/update
    defaults: { _controller: "RudakPartnerBundle:Category:update" }
    requirements: { _method: post|put }

admin_partners_categ_delete:
    path:     /{id}/delete
    defaults: { _controller: "RudakPartnerBundle:Category:delete" }
    requirements: { _method: post|delete }
